# Project information
site_name: Nifi Monitoring Splunk
site_author: Kudaw S.A.
site_description: Nifi Monitoring Splunk Documentation
site_url: https://kudawdev.github.io/nifi-monitoring-splunk/

# Copyright
copyright: Copyright &copy; 2021 Kudaw S.A. All Rights Reserved

# Repository information
repo_url: https://github.com/kudawdev/PRD-nifi-monitoring-splunk
repo_name: NIFI Monitoring Splunk

# Navigation
nav:
  - Introduction: index.md
  - Overview: overview.md
  - Install and configure NIFI Monitoring on Splunk: installation.md
  - NIFI Configuration: configuration.md
  - Data Reference: references.md
  - Contribute: contributing.md

# Configuration
theme: 
  name: material # readthedocs material
  #custom_dir: docs/theme/material
  language: en
  locale: en
  logo: assets/images/nifi.png
  favicon: assets/images/favicon.ico
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant

# Extras
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://www.kudaw.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kudaw-latam
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kudaw
    - icon: fontawesome/brands/github
      link: https://github.com/kudawdev
  current_version: 1.0
  alternate:
    # Switch to English
    - name: English
      link: ""
      lang: en
    # Switch to Spanish
    - name: Español
      link: /es/
      lang: es

extra_javascript:
- assets/js/theme.js
extra_css:
- assets/css/theme.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      
# Plugins
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        es: Spanish
      nav_translations:
        es:
          Introduction: Introducción
          Overview: Vista General
          Install and configure NIFI Monitoring on Splunk: Instalación y configuración de NIFI Monitoring en Splunk
          NIFI Configuration: Configuración de NIFI
          Data Reference: Referencia de Datos
          Contribute: Contribuya